language: node_js
node_js:
  - "0.10"
install:
  - travis_retry npm install -g grunt-cli@0.1.9
  - travis_retry npm install
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  - TEST_CMD: test:unit
  - TEST_CMD: shell:cheapseats:--range:0..80
  - TEST_CMD: shell:cheapseats:--range:80..
script: "grunt $TEST_CMD"
matrix:
  fast_finish: true
